### ISSUE TITLE
Describe effects of connection migration with a proxy

### ISSUE THREAD

**Issue by tfpauly** [ietf-wg-masque/draft-ietf-masque-connect-udp#42] opened 2021-03-05 16:19 UTC
Jana and I were discussing some interesting effects of doing QUIC connection migration to a CONNECT-UDP proxy when the target server is running QUIC. I think the document should have a section to discuss considerations for migration.

In general, doing QUIC migration to a proxy is great, since it allows connections to migrate even when the target server may not support migration (which is particularly useful for TCP origins where you proxy via CONNECT). However, this also has the effect of hiding a migration event from a QUIC origin.

A QUIC server responding to migration should reset its congestion window state, and ensure that it is conservative in sending until the new path is validated. The proxy can certainly do this, but a QUIC target origin won't know that this event has occurred, and may be sending quite a lot of data which will now be either queued at the proxy or dropped. We should have recommended behavior for the proxy to effectively get the target to slow down and recognize the congestion reset event. This may "just work" depending on how the proxy is implemented, but there could also be pitfalls.

**Comment by DavidSchinazi** [comment] 2021-03-05 16:32
That's a good point, we should mention this in the draft. One solution could be to have the proxy switch target-facing UDP port and perform migration to the target server any time it sees a migration from the client.

**Comment by tfpauly** [comment] 2021-03-05 16:53
Yes, you can switch the port, but as Jana pointed out, that will look more like NAT rebinding, which may not cause all servers to fully reset their congestion.

**Comment by DavidSchinazi** [comment] 2021-03-05 17:37
That's true, though I'm not sure there's much else the proxy can do? As long as the proxy behaves correctly on the client-facing connection (by resetting the congestion controller there therefore dropping incoming UDP packets that don't fit in the congestion window), this will just cause a burst of packet loss and the target server should react to that in one or two round trips.

**Comment by tfpauly** [comment] 2021-03-05 17:59
Yes, I agree that that's likely the correct outcome here. I think the text mainly should describe that, mention you can change the port if you want to provide a bit of a signal, and also warn against queuing the packets at the proxy excessively. That last part should be done anyhow, but this case is one where even if the proxy has room in its buffers, it should be pretty aggressive about dropping to make the loss event obvious.

**Comment by LPardue** [comment] 2021-03-05 19:32
I agree with documenting this case for the proxy, although I might have opinions on any specific guidance. 

I wonder, more generally, if it would help to have an independent QUIC extension frame that endpoints can use to signal the other one that "something happened" . This would allow the client, fully aware of what it just did, to tell the remote endpoint that something happened which might invalidate present state or asumptions about congestion-control state, PMTUD etc.

**Comment by DavidSchinazi** [comment] 2021-03-05 22:37
@tfpauly I just noticed #14. Should we mark this issue as a duplicate of that one and move the discussion there?

**Closed** 2021-10-06 21:33 UTC
